# Generated by Django 5.2.3 on 2026-05-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='photo',
        ),
    ]
