# Generated by Django 5.2.3 on 2026-05-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_animal_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='is_active',
        ),
    ]
