# Generated by Django 5.2.3 on 2026-05-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_animal_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='chip_number',
        ),
    ]
