# Generated by Django 5.2.3 on 2026-05-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_remove_animal_chip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='chip_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер чипа'),
        ),
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='chronic_diseases',
            field=models.TextField(blank=True, verbose_name='Хронічні захворювання'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Нотатки'),
        ),
    ]
