# Generated by Django 5.2.3 on 2026-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_uk',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Назва (укр)'),
        ),
    ]
