# Generated by Django 5.2.3 on 2026-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_species_name_alter_species_name_uk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='chip_number',
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Самець'), ('female', 'Самиця')], max_length=10, null=True),
        ),
    ]
