# Generated by Django 5.2.3 on 2026-05-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_remove_animal_chip_number_alter_animal_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='photo',
        ),
    ]
