# Generated by Django 5.2.3 on 2026-05-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Діагноз / Опис')),
                ('prescription', models.TextField(blank=True, verbose_name='Призначення')),
                ('weight_at_visit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вага на момент візиту')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Температура')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Візит',
                'verbose_name_plural': 'Візити',
                'ordering': ['-appointment__date', '-created_at'],
            },
        ),
    ]
