# Generated by Django 5.2.3 on 2026-05-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='weight_at_visit',
        ),
    ]
