# Generated by Django 5.2.3 on 2026-05-06 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0005_animal_chip_number_animal_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200, verbose_name='Назва вакцини')),
                ('date_given', models.DateField(blank=True, null=True, verbose_name='Дата проведення')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Дата наступної вакцинації')),
                ('status', models.CharField(choices=[('planned', 'Заплановано'), ('completed', 'Виконано'), ('overdue', 'Прострочено')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вакцинація',
                'verbose_name_plural': 'Вакцинації',
                'ordering': ['-date_given', 'next_date'],
            },
        ),
    ]
