# Generated by Django 5.2.3 on 2026-05-06 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccination',
            options={'ordering': ['-date_given'], 'verbose_name': 'Вакцинація', 'verbose_name_plural': 'Вакцинації'},
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Серія препарату'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccine_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тип вакцини'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date_given',
            field=models.DateField(default='2026-05-06', verbose_name='Дата проведення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='next_date',
            field=models.DateField(blank=True, null=True, verbose_name='Наступна дата'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='status',
            field=models.CharField(choices=[('done', 'Виконано'), ('planned', 'Заплановано'), ('overdue', 'Прострочено')], default='done', max_length=10),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='vet',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
