# Generated by Django 5.2.3 on 2026-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0002_alter_vaccination_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
