# Generated by Django 5.2.3 on 2026-05-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0003_vaccination_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='vaccine_type',
        ),
    ]
